apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "koptim-scheduler.labels" . | nindent 4 }}
  name: {{ include "koptim-scheduler.fullname" . }}
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
      - watch
      - list
      - get
