apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koptim-scheduler.fullname" . }}
  namespace: kube-system
  labels:
    component: scheduler
    tier: control-plane
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "koptim-scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-second-scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
          - /usr/local/bin/kube-scheduler
          - --address=0.0.0.0
          - --leader-elect=false
          - --scheduler-name={{ include "koptim-scheduler.fullname" . }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: 100m
          securityContext:
            privileged: false
          volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
      {{- with .Values.nodeSelector }}
      nodeSelector:
        #disktype: ssd
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
