apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "koptim-criteria.labels" . | nindent 4 }}
  name: {{ include "koptim-criteria.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
      - pods
      - endpoints
      - namespaces
      - daemonset
      - deployments
      - statefulsets
      - replicasets
      - update
    verbs:
      - get
      - list
      - watch
      - delete
      - update
      - edite
      - patch
      - annotate
  - apiGroups:
      - "apps"
    resources:
      - nodes
      - services
      - pods
      - endpoints
      - namespaces
      - daemonset
      - deployments
      - statefulsets
      - replicasets
      - update
    verbs:
      - get
      - list
      - watch
      - delete
      - update
      - edite
      - patch
      - annotate
